docs: Inline Code Documentations
input-output-hk/atala-prism-wallet-sdk-kmm pull request #119
Opened 2023-12-13 12:25 UTC by hamada147

# Overview
- Wrote a lot of documentation to improve the overall docs
- Improved Custom Exceptions to show errors
- Added missing `@JvmStatic`
- Added missing `@JvmOverloads`

Fixes: 

- [ATL-6286]
- [ATL-6287]
- [ATL-6288]
- [ATL-6289]

## Checklist

### My PR contains...
* [ ] No code changes (changes to documentation, CI, metadata, etc.)
* [x] Bug fixes (non-breaking change which fixes an issue)
* [x] Improvements (misc. changes to existing features)
* [ ] Features (non-breaking change which adds functionality)

### My changes...
* [ ] are breaking changes
* [x] are not breaking changes
* [ ] If yes to above: I have updated the documentation accordingly

### Documentation
* [ ] My changes do not require a change to the project documentation
* [x] My changes require a change to the project documentation
* [x] If yes to above: I have updated the documentation accordingly

### Tests
* [x] My changes can not or do not need to be tested
* [ ] My changes can and should be tested by unit and/or integration tests
* [ ] If yes to above: I have added tests to cover my changes
* [ ] If yes to above: I have taken care to cover edge cases in my tests

[ATL-6286]: https://input-output.atlassian.net/browse/ATL-6286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATL-6287]: https://input-output.atlassian.net/browse/ATL-6287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATL-6288]: https://input-output.atlassian.net/browse/ATL-6288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATL-6289]: https://input-output.atlassian.net/browse/ATL-6289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-12-13 12:35 UTC, atala-dev commented
### Code Coverage
|File|Coverage [31.03%]|
|:-|:-:|
|[atala-prism-sdk/src/androidMain/kotlin/io/iohk/atala/prism/walletsdk/pluto/data/DbConnection.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FandroidMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fpluto%2Fdata%2FDbConnection.kt)|0.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/ApolloImpl.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2FApolloImpl.kt)|57.14%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/config/ECConfig.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Fconfig%2FECConfig.kt)|0.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/helpers/ByteArrayExt.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Fhelpers%2FByteArrayExt.kt)|0.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/helpers/JVMBigIntegerExt.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Fhelpers%2FJVMBigIntegerExt.kt)|0.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/utils/Ed25519KeyPair.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Futils%2FEd25519KeyPair.kt)|100.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/utils/Ed25519PrivateKey.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Futils%2FEd25519PrivateKey.kt)|35.71%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/utils/Ed25519PublicKey.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Futils%2FEd25519PublicKey.kt)|38.46%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/utils/JVMBigIntegerExt.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Futils%2FJVMBigIntegerExt.kt)|0.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/utils/Secp256k1KeyPair.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Futils%2FSecp256k1KeyPair.kt)|100.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/utils/Secp256k1PrivateKey.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Futils%2FSecp256k1PrivateKey.kt)|50.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/utils/Secp256k1PublicKey.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Futils%2FSecp256k1PublicKey.kt)|50.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/utils/X25519KeyPair.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Futils%2FX25519KeyPair.kt)|100.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/utils/X25519PrivateKey.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Futils%2FX25519PrivateKey.kt)|30.77%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/utils/X25519PublicKey.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Futils%2FX25519PublicKey.kt)|33.33%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/utils/ec/KMMECCoordinate.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Futils%2Fec%2FKMMECCoordinate.kt)|0.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/utils/ec/KMMECPoint.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fapollo%2Futils%2Fec%2FKMMECPoint.kt)|0.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/castor/CastorImpl.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fcastor%2FCastorImpl.kt)|38.71%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/castor/did/DIDParser.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fcastor%2Fdid%2FDIDParser.kt)|81.82%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/castor/did/DIDUrlParser.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fcastor%2Fdid%2FDIDUrlParser.kt)|87.50%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/castor/did/prismdid/LongFormPrismDID.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fcastor%2Fdid%2Fprismdid%2FLongFormPrismDID.kt)|0.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/castor/did/prismdid/PrismDIDMethodId.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fcastor%2Fdid%2Fprismdid%2FPrismDIDMethodId.kt)|50.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/castor/did/prismdid/PrismDIDPublicKey.kt](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/0077e5ae51d9c815ee4f6ba63f4d745a66834358/atala-prism-sdk%2Fsrc%2FcommonMain%2Fkotlin%2Fio%2Fiohk%2Fatala%2Fprism%2Fwalletsdk%2Fcastor%2Fdid%2Fprismdid%2FPrismDIDPublicKey.kt)|0.00%|
|[atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/castor/resolvers/LongFormP [...]

2023-12-13 17:08 UTC, petevielhaber approved these changes

2023-12-13 17:11 UTC, petevielhaber commented on atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/Errors.kt
> + * A class representing an unknown error in a Prism.
```suggestion
 * A class representing an unknown error in a PRISM.
```

2023-12-13 17:42 UTC, petevielhaber commented on atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/VerifiableCredential.kt
> + * Note: The CredentialType enum is used to indicate the type of verifiable credential.
```suggestion
::: info

 The CredentialType enum is used to indicate the type of verifiable credential.
 
 :::
```

2023-12-13 17:42 UTC, petevielhaber commented on atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/Errors.kt
> + * A class representing a known error in a Prism.
```suggestion
 * A class representing a known error in a PRISM.
```

2023-12-13 17:43 UTC, petevielhaber commented on atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/Errors.kt
> + * A class representing a common error in a Prism.
```suggestion
 * A class representing a common error in a PRISM.
```

2023-12-13 17:43 UTC, petevielhaber commented on atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/Errors.kt
> +     * This error occurs when one or more mnemonic words are invalid in a Prism API response.
```suggestion
     * This error occurs when one or more mnemonic words are invalid in a PRISM API response.
```

2023-12-13 17:44 UTC, petevielhaber commented on atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/Errors.kt
> +     * A class representing an invalid JSON Web Key (JWK) error in the Prism SDK.
```suggestion
     * A class representing an invalid JSON Web Key (JWK) error in the PRISM SDK.
```

2023-12-13 17:44 UTC, petevielhaber commented on atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/Errors.kt
> +     * Represents an error that occurs when the long form prism DID is invalid or changed.
```suggestion
     * Represents an error that occurs when the long form PRISM DID is invalid or changed.
```

2023-12-13 17:44 UTC, petevielhaber commented on atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/Errors.kt
> +     * Represents an error that occurs when the initial state of a Prism DID changes,
```suggestion
     * Represents an error that occurs when the initial state of a PRISM DID changes,
```

2023-12-13 17:45 UTC, petevielhaber commented on atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/Errors.kt
> +     * A class representing a DIDComm error in the Prism SDK.
```suggestion
     * A class representing a DIDComm error in the PRISM SDK.
```

2023-12-13 17:46 UTC, petevielhaber commented on atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/Errors.kt
> +     * Represents an error that occurs when attempting to create a JWT presentation without providing a Prism DID.
```suggestion
     * Represents an error that occurs when attempting to create a JWT presentation without providing a PRISM DID.
```

2023-12-13 17:48 UTC, petevielhaber commented on atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/Errors.kt
> +     * A class representing an error when no domain or challenge is found as part of the offer json.
```suggestion
     * A class representing an error when no domain or challenge is found as part of the offer JSON.
```

2023-12-13 17:56 UTC, petevielhaber commented on atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/protocols/outOfBand/PrismOnboardingInvitation.kt
> + * Represents an onboarding invitation for Prism.
```suggestion
 * Represents an onboarding invitation for PRISM.
```

2023-12-13 17:58 UTC, petevielhaber commented on atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/protocols/prismOnboarding/PrismOnboardingInvitation.kt
> + * Represents an onboarding invitation in Prism.
```suggestion
 * Represents an onboarding invitation in PRISM.
```

2023-12-13 17:58 UTC, petevielhaber commented on atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/protocols/prismOnboarding/PrismOnboardingInvitation.kt
> + * This class is responsible for parsing and storing the information from a Prism onboarding invitation.
```suggestion
 * This class is responsible for parsing and storing the information from a PRISM onboarding invitation.
```

2023-12-13 18:00 UTC, petevielhaber requested changes
- Need an admonition instead of note; added suggestion for review.

2023-12-18 13:17 UTC, petevielhaber approved these changes

2023-12-19 08:58 UTC, merged