docs: renmaing
input-output-hk/atala-prism-wallet-sdk-kmm pull request #153
Opened 2024-05-15 10:47 UTC by hamada147

### Description: 
Summarize the changes you're submitting in a few sentences, including Jira ticket ATL-xxxx if applicable.
Link to any discussion, related issues and bug reports to give the context to help the reviewer understand the PR.

### Alternatives Considered (optional): 
Link to existing ADR (Architecture Decision Record), if any. If relevant, describe other approaches explored and the selected approach. Documenting why the methods were not selected will create a knowledge base for future reference, helping prevent others from revisiting less optimal ideas.

### Checklist: 
- [ ] My PR follows the [contribution guidelines](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/main/CONTRIBUTING.md) of this project
- [ ] My PR is free of third-party dependencies that don't comply with the [Allowlist](https://toc.hyperledger.org/governing-documents/allowed-third-party-license-policy.html#approved-licenses-for-allowlist)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked the PR title to follow the [conventional commit specification](https://www.conventionalcommits.org/en/v1.0.0/)

2024-05-15 13:29 UTC, petevielhaber approved these changes
- Unable to complete review. Almost 3,900 files changed. Will review written portions post-merge.

2024-05-15 16:34 UTC, mkbreuningIOHK requested changes

2024-05-15 16:34 UTC, mkbreuningIOHK commented on CONTRIBUTING.md
> +### Identus KMM SDK
`Identus KMM SDK` should be `Edge Agent SDK KMM` according to the [replacement table](https://docs.google.com/spreadsheets/d/1lR3abdg6qExXasUVqBlFouNu9FCB0I1ynMMZodQ6y8U/edit#gid=0)

2024-05-15 16:34 UTC, mkbreuningIOHK commented on CONTRIBUTING.md
> +Unsure where to begin contributing to Identus KMM SDK? You can start by looking through the [Readme](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/main/README.md) that provides a
`Identus KMM SDK` should be `Edge Agent SDK KMM` according to the [replacement table](https://docs.google.com/spreadsheets/d/1lR3abdg6qExXasUVqBlFouNu9FCB0I1ynMMZodQ6y8U/edit#gid=0)

2024-05-15 16:34 UTC, mkbreuningIOHK commented on CONTRIBUTING.md
> +Identus KMM software development kit will help adoption within Kotlin platforms (Java/Android) by providing key functionalities. For more information about the SDK, please have a look at the [Readme]
`Identus KMM SDK` should be `Edge Agent SDK KMM` according to the [replacement table](https://docs.google.com/spreadsheets/d/1lR3abdg6qExXasUVqBlFouNu9FCB0I1ynMMZodQ6y8U/edit#gid=0)

2024-05-15 16:34 UTC, mkbreuningIOHK commented on CONTRIBUTING.md
> +This section guides you through submitting a bug report for Identus KMM SDK. Following these guidelines helps maintainers and the community understand your report :pencil:, reproduce the behaviour :c
`Identus KMM SDK` should be `Edge Agent SDK KMM` according to the [replacement table](https://docs.google.com/spreadsheets/d/1lR3abdg6qExXasUVqBlFouNu9FCB0I1ynMMZodQ6y8U/edit#gid=0)

2024-05-15 16:34 UTC, mkbreuningIOHK commented on README.md
> +# Welcome to Identus Kotlin Multiplatform SDK (Android/JVM)
Welcome to Edge Agent

2024-05-15 16:34 UTC, mkbreuningIOHK commented on README.md
> +Identus.
Why  return to line?

2024-05-15 16:34 UTC, mkbreuningIOHK commented on README.md
> +Cardano, it offers core infrastructure for issuing DIDs (Decentralized identifiers) and verifiable credentials,
Why return to line?

2024-05-15 16:34 UTC, mkbreuningIOHK commented on README.md
> +* [atala-prism-building-blocks](https://github.com/hyperledger-labs/open-enterprise-agent) - Repo that contains the
Bad indentation / layout and the repo can be changed to identus-cloud-agent

2024-05-15 16:34 UTC, mkbreuningIOHK commented on README.md
> +Identus Kotlin multiplatform SDK provides the following building blocks to create, manage and resolve decentralized
`Identus KMM SDK` should be `Edge Agent SDK KMM` according to the [replacement table](https://docs.google.com/spreadsheets/d/1lR3abdg6qExXasUVqBlFouNu9FCB0I1ynMMZodQ6y8U/edit#gid=0)

2024-05-15 16:34 UTC, mkbreuningIOHK commented on README.md
> +interactions between DIDs, and store, manage, and recover verifiable data linked to DIDs.
Why return to line?

2024-05-15 16:34 UTC, mkbreuningIOHK commented on README.md
> +To get started with the Identus kotlin multiplatform SDK, you can set up the SDK and start a new project or integrate it
`Identus KMM SDK` should be `Edge Agent SDK KMM` according to the [replacement table](https://docs.google.com/spreadsheets/d/1lR3abdg6qExXasUVqBlFouNu9FCB0I1ynMMZodQ6y8U/edit#gid=0)

2024-05-15 16:34 UTC, mkbreuningIOHK commented on build.gradle.kts
> +                        name.set("Identus Edge Agent SDK")
No need of Identus I think. Just Edge Agent

2024-05-15 16:34 UTC, mkbreuningIOHK commented on edge-agent-sdk/build.gradle.kts
> +    description = "This is a Kotlin Multiplatform implementation of Identus Edge Agent KMM"
Not sure how AtalaPrismSDK should be renamed: EdgeAgentSDK?

2024-05-15 17:23 UTC, hamada147 commented on edge-agent-sdk/docs/EdgeAgentSDK.md
> +Identus KMP SDK is a library and documentation that helps developers build KMM/JVM/Android SSI (self-sovereign
**KMP**: Kotlin Multiplatform
**KMM**: Kotlin Multiplatform Mobile
In our case it will be **KMP**

2024-05-20 10:10 UTC, closed without merging

2024-05-20 15:08 UTC, mkbreuningIOHK commented on CONTRIBUTING.md
> +The following is a set of guidelines for contributing to Identus KMM SDK. These are mostly guidelines. Use your best judgment, and feel free to propose changes to this document in a pull request.
Updated in the main branch.

2024-05-20 15:09 UTC, mkbreuningIOHK commented on CONTRIBUTING.md
> +  * [Identus KMM SDK](#Identus-kmm)
Updated in the main branch.

2024-05-20 15:10 UTC, mkbreuningIOHK commented on CONTRIBUTING.md
>  * [atala-prism-building-blocks](https://github.com/hyperledger-labs/open-enterprise-agent) - Repo that contains the servers Building Blocks.
Updated in the main branch.

2024-05-20 15:10 UTC, mkbreuningIOHK commented on CONTRIBUTING.md
> +### Identus KMM SDK
Updated in the main branch.

2024-05-20 15:11 UTC, mkbreuningIOHK commented on CONTRIBUTING.md
> +Unsure where to begin contributing to Identus KMM SDK? You can start by looking through the [Readme](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/blob/main/README.md) that provides a
Updated in the main branch.

2024-05-20 15:29 UTC, mkbreuningIOHK commented on edge-agent-sdk/build.gradle.kts
> +    description = "This is a Kotlin Multiplatform implementation of Identus Edge Agent KMM"
Updated in the main branch.

2024-05-20 15:29 UTC, mkbreuningIOHK commented on edge-agent-sdk/docs/EdgeAgentSDK.md
> +Identus KMP SDK is a library and documentation that helps developers build KMM/JVM/Android SSI (self-sovereign
Updated in the main branch.

2024-05-20 15:52 UTC, mkbreuningIOHK commented on edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/castor/did/prismdid/PrismDIDPublicKey.kt
> + * Represents a public key for the Identus system.
I did that in the PR https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/pull/154

2024-05-20 15:53 UTC, mkbreuningIOHK commented
All conversations are resolved when reviewing the main branch. See https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/pull/154 as a follow-up.